services:
  database:
    image: mariadb:latest
    environment:
        MYSQL_DATABASE: maBDD
        MYSQL_ROOT_PASSWORD: monPass
      
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql:rw

  phpmyadmin:
      depends_on:
          - database
      image: phpmyadmin:latest
      restart: always
      ports:
          - 8085:80
      environment:
          PMA_HOST: database
          PMA_USER: root
          PMA_PASSWORD: monPass

  mailer:
    image: axllent/mailpit:latest
    ports:
      - 1025:1025
      - 8025:8025
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: monPass

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: monPass
      ME_CONFIG_MONGODB_URL: mongodb://root:monPass@mongo:27017/
      ME_CONFIG_BASICAUTH: false

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
