# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    env(MONGODB_URL): ''
    env(MONGODB_DB): ''

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    # === Repositories ODM en services ===
    App\Repository\ChambreRepository:
        factory: ['@doctrine_mongodb.odm.document_manager', getRepository]
        arguments: [App\Document\Chambre]
        public: false

    App\Repository\ReservationRepository:
        factory: ['@doctrine_mongodb.odm.document_manager', getRepository]
        arguments: [App\Document\Reservation]
        public: false
    App\Security\MongoUserProvider:
        arguments:
            $dm: '@doctrine_mongodb.odm.document_manager'
        tags: [ 'security.user_provider' ]

    # === Services métier ===
    App\Service\AvailabilityService:
        public: true
        arguments:
            $dm: '@doctrine_mongodb.odm.document_manager'
            $chambreRepo: '@App\Repository\ChambreRepository'
            $reservationRepo: '@App\Repository\ReservationRepository'

    App\Service\ReservationNumberGenerator:
        public: true

    App\Service\ReservationService:
        public: true
        arguments:
            $dm: '@doctrine_mongodb.odm.document_manager'
            $availability: '@App\Service\AvailabilityService'
            $numberGen: '@App\Service\ReservationNumberGenerator'
    App\Command\DemoReservationCommand:
        tags: [ 'console.command' ]
    # === Bind des interfaces vers implémentations ===
    App\Domain\AvailabilityServiceInterface: '@App\Service\AvailabilityService'
    App\Domain\ReservationNumberGeneratorInterface: '@App\Service\ReservationNumberGenerator'
    App\Domain\ReservationServiceInterface: '@App\Service\ReservationService'