security:
  password_hashers:
    App\Document\Client: 'auto'

  providers:
    app_mongo_provider:
      id: App\Security\MongoUserProvider

  firewalls:
    main:
      lazy: true
      provider: app_mongo_provider
      form_login:
        login_path: app_login
        check_path: app_login
        enable_csrf: false            # pratique pour Postman en dev
        username_parameter: email     # tu postes "email"
        password_parameter: password  # tu postes "password"
        default_target_path: /client/reservations
      logout:
        path: app_logout
        target: /

  access_control:
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/client, roles: [ROLE_CLIENT, ROLE_ADMIN] }
